apiVersion: v1
kind: Service
metadata:
  name:  postgres-staging
  labels:
    app: postgres
spec:
  type:  LoadBalancer
  selector:
    app:  postgres
  ports:
  - name:  postgres-node
    port:  5432
    targetPort:  5432
    nodePort: 31516
